/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CustomerWorkArea;

import AppSystem.ApplicationSystem;
import Books.Book;
import Customer.Customer;
import General.Magazine;
import LibrarianArea.Library;
import LibrarianArea.UserAccount;
import Materials.Material;
import Services.RentalRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author nishipancholi
 */
public class MakeRequestsJPanel extends javax.swing.JPanel {

    private UserAccount useraccount;
    private ApplicationSystem system;
    private Library lib;
    /**
     * Creates new form MakeRequestsJPanel
     */
    public MakeRequestsJPanel() {
        initComponents();
    }

    MakeRequestsJPanel(ApplicationSystem system, UserAccount useraccount, Library lib) {
       initComponents();
       this.system = system;
       this.useraccount = useraccount;
       this.lib=lib;
       populateDropdown();
       populateMaterialName();
    }

    public void populateDropdown(){
        String materialSelected =(String) chooseComboBox.getSelectedItem();
        ArrayList<Book> bookList= this.lib.getBookdirectory().getBooklist();
        ArrayList<Magazine> magList= this.lib.getMagazineDirectory().getMagazinelist();
        if(materialSelected=="book"){
            materialsComboBox.removeAllItems();
            for(Book b:bookList){
                if(b.isIsAvailable()){
                  materialsComboBox.addItem(b);
                }
            }    
        }
        else{
            materialsComboBox.removeAllItems();
            for(Magazine mag:magList){
                if(mag.isIsAvailable()){
                  materialsComboBox.addItem(mag);
                }
            }
        }
        
    }
    public void populateMaterialName(){
        Material materialSelected =(Material) materialsComboBox.getSelectedItem();
        if(materialSelected!=null){
            materialNameField.setText(materialSelected.getName());
        }
        else{
            materialNameField.setText("");
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooseComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        materialsComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        materialNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        durationComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chooseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "book", "magazine" }));
        chooseComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chooseComboBoxItemStateChanged(evt);
            }
        });
        chooseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseComboBoxActionPerformed(evt);
            }
        });
        add(chooseComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 46, 217, -1));

        jLabel1.setText("Select a material type you want to rent:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 23, -1, -1));

        materialsComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                materialsComboBoxItemStateChanged(evt);
            }
        });
        add(materialsComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 220, -1));

        jLabel2.setText("Selected Material Name Is:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));
        add(materialNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 230, -1));

        jLabel3.setText("Choose material:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jButton1.setText("Place Request");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        durationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "weekly", "monthly", "quaterly" }));
        add(durationComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 200, -1));

        jLabel4.setText("Choose Duration:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void chooseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseComboBoxActionPerformed

    private void chooseComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chooseComboBoxItemStateChanged
        // TODO add your handling code here:
        populateDropdown();
    }//GEN-LAST:event_chooseComboBoxItemStateChanged

    private void materialsComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_materialsComboBoxItemStateChanged
        // TODO add your handling code here:
        populateMaterialName();
    }//GEN-LAST:event_materialsComboBoxItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String materialSelected =(String) chooseComboBox.getSelectedItem();
        Material mat =(Material) materialsComboBox.getSelectedItem();
        String duration= (String) durationComboBox.getSelectedItem();
        mat.setIsAvailable(false);
        Customer c = this.system.getCustomerDirectory().findById(useraccount.getAccountId());
        RentalRequest request = c.getRentalRequestDirectory().createRequest(c,mat, "Requested", duration, materialSelected);
        JOptionPane.showMessageDialog(null, "Request Created.");
        
        populateDropdown();
        populateMaterialName();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> chooseComboBox;
    private javax.swing.JComboBox durationComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField materialNameField;
    private javax.swing.JComboBox materialsComboBox;
    // End of variables declaration//GEN-END:variables
}
