/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author nishipancholi
 */
public class ChefRecipe extends javax.swing.JFrame {

    /**
     * Creates new form ChefReceipe
     */
    public ChefRecipe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        mainJSplitPane = new javax.swing.JSplitPane();
        leftJPanel = new javax.swing.JPanel();
        createBtn = new javax.swing.JButton();
        readBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        heading = new javax.swing.JLabel();
        rightJPanel = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        tagLine = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftJPanel.setBackground(new java.awt.Color(204, 204, 255));
        leftJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createBtn.setBackground(new java.awt.Color(51, 0, 51));
        createBtn.setFont(new java.awt.Font("Khmer MN", 0, 13)); // NOI18N
        createBtn.setForeground(new java.awt.Color(255, 255, 255));
        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        leftJPanel.add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 94, -1, -1));

        readBtn.setBackground(new java.awt.Color(51, 0, 51));
        readBtn.setFont(new java.awt.Font("Khmer MN", 0, 13)); // NOI18N
        readBtn.setForeground(new java.awt.Color(255, 255, 255));
        readBtn.setText("Read");
        readBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readBtnActionPerformed(evt);
            }
        });
        leftJPanel.add(readBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 150, -1, -1));

        updateBtn.setBackground(new java.awt.Color(51, 0, 51));
        updateBtn.setFont(new java.awt.Font("Khmer MN", 0, 13)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        leftJPanel.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 211, -1, -1));

        heading.setFont(new java.awt.Font("Impact", 0, 13)); // NOI18N
        heading.setForeground(new java.awt.Color(51, 0, 51));
        heading.setText("CHEF'S RECIPE");
        leftJPanel.add(heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 24, -1, -1));

        mainJSplitPane.setLeftComponent(leftJPanel);

        rightJPanel.setBackground(new java.awt.Color(255, 204, 204));
        rightJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setFont(new java.awt.Font("Jaini", 3, 13)); // NOI18N
        header.setForeground(new java.awt.Color(153, 153, 0));
        header.setText("WELCOME TO CHEF'S RECIPE");
        rightJPanel.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 83, -1, -1));

        description.setFont(new java.awt.Font("Kaiti SC", 2, 13)); // NOI18N
        description.setForeground(new java.awt.Color(0, 153, 153));
        description.setText("One Stop to All the Food Recipes.....");
        rightJPanel.add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 201, -1, -1));

        tagLine.setFont(new java.awt.Font("Klee", 0, 13)); // NOI18N
        tagLine.setForeground(new java.awt.Color(0, 102, 102));
        tagLine.setText("Good Food Good Mood!");
        rightJPanel.add(tagLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 226, -1, -1));

        mainJSplitPane.setRightComponent(rightJPanel);

        getContentPane().add(mainJSplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        mainJSplitPane.setRightComponent(new CreateJPanel());
    }//GEN-LAST:event_createBtnActionPerformed

    private void readBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readBtnActionPerformed
        // TODO add your handling code here:
        mainJSplitPane.setRightComponent(new ReadJPanel());
    }//GEN-LAST:event_readBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        mainJSplitPane.setRightComponent(new UpdateJPanel());
    }//GEN-LAST:event_updateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChefRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChefRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChefRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChefRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChefRecipe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel description;
    private javax.swing.JLabel header;
    private javax.swing.JLabel heading;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel leftJPanel;
    private javax.swing.JSplitPane mainJSplitPane;
    private javax.swing.JButton readBtn;
    private javax.swing.JPanel rightJPanel;
    private javax.swing.JLabel tagLine;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
