/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.ChefRecipe;
import Model.Recipe;
import Model.Validations;
import java.awt.Image;
import java.io.File;
import java.util.UUID;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author nishipancholi
 */
public class CreateJPanel extends javax.swing.JPanel {

    private ChefRecipe chefRecipeDetails;
    private Validations validation;
    private String selectedPath;
    private boolean glutenFree;

    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel() {
        initComponents();

    }

    CreateJPanel(ChefRecipe chefRecipeDetails) {
        initComponents();
        this.chefRecipeDetails = chefRecipeDetails;
        this.validation = new Validations();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yesNoButtonGroup = new javax.swing.ButtonGroup();
        header = new javax.swing.JLabel();
        chefFirstNameLabel = new javax.swing.JLabel();
        chefLastNameLabel = new javax.swing.JLabel();
        chefUserNameLabel = new javax.swing.JLabel();
        recipeLabel = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        servingNoLabel = new javax.swing.JLabel();
        glutenLabel = new javax.swing.JLabel();
        difficultyLabel = new javax.swing.JLabel();
        catFoodLabel = new javax.swing.JLabel();
        imgLabel = new javax.swing.JLabel();
        ingredientsLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        chefFirstNameField = new javax.swing.JTextField();
        chefLastNameField = new javax.swing.JTextField();
        chefUserNameField = new javax.swing.JTextField();
        chefEmailField = new javax.swing.JTextField();
        servingsField = new javax.swing.JTextField();
        chefPhoneField = new javax.swing.JTextField();
        recipeTitleField = new javax.swing.JTextField();
        ingredientsField = new javax.swing.JTextField();
        difficultyField = new javax.swing.JTextField();
        categoryFoodField = new javax.swing.JTextField();
        descriptionField = new javax.swing.JTextField();
        yesRadioButton = new javax.swing.JRadioButton();
        noRadioButton = new javax.swing.JRadioButton();
        browseBtn = new javax.swing.JButton();
        imgDisplayField = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        addRecipeBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(102, 0, 0));
        header.setFont(new java.awt.Font("Hubballi", 3, 18)); // NOI18N
        header.setText("Create Your Own");
        add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 6, -1, -1));

        chefFirstNameLabel.setBackground(new java.awt.Color(51, 0, 153));
        chefFirstNameLabel.setFont(new java.awt.Font("New Peninim MT", 2, 12)); // NOI18N
        chefFirstNameLabel.setForeground(new java.awt.Color(102, 0, 102));
        chefFirstNameLabel.setText("Chef's First Name:");
        add(chefFirstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 42, -1, -1));

        chefLastNameLabel.setBackground(new java.awt.Color(51, 0, 153));
        chefLastNameLabel.setFont(new java.awt.Font("New Peninim MT", 2, 12)); // NOI18N
        chefLastNameLabel.setForeground(new java.awt.Color(102, 0, 102));
        chefLastNameLabel.setText("Chef's Last Name:");
        add(chefLastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 70, -1, 23));

        chefUserNameLabel.setBackground(new java.awt.Color(51, 0, 153));
        chefUserNameLabel.setFont(new java.awt.Font("New Peninim MT", 2, 12)); // NOI18N
        chefUserNameLabel.setForeground(new java.awt.Color(102, 0, 102));
        chefUserNameLabel.setText("Username:");
        add(chefUserNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 103, -1, 23));

        recipeLabel.setBackground(new java.awt.Color(51, 0, 153));
        recipeLabel.setFont(new java.awt.Font("Noteworthy", 3, 18)); // NOI18N
        recipeLabel.setForeground(new java.awt.Color(102, 0, 102));
        recipeLabel.setText("Recipe");
        add(recipeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 236, 71, 27));

        contactLabel.setBackground(new java.awt.Color(51, 0, 153));
        contactLabel.setFont(new java.awt.Font("New Peninim MT", 3, 12)); // NOI18N
        contactLabel.setForeground(new java.awt.Color(102, 0, 102));
        contactLabel.setText("CONTACT INFORMATION");
        add(contactLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 159, 20));

        phoneLabel.setBackground(new java.awt.Color(51, 0, 153));
        phoneLabel.setFont(new java.awt.Font("New Peninim MT", 2, 12)); // NOI18N
        phoneLabel.setForeground(new java.awt.Color(102, 0, 102));
        phoneLabel.setText("Phone No:");
        add(phoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 23));

        emailLabel.setBackground(new java.awt.Color(51, 0, 153));
        emailLabel.setFont(new java.awt.Font("New Peninim MT", 2, 12)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(102, 0, 102));
        emailLabel.setText("Email ID:");
        add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 23));

        titleLabel.setBackground(new java.awt.Color(51, 0, 153));
        titleLabel.setFont(new java.awt.Font("New Peninim MT", 2, 12)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(102, 0, 102));
        titleLabel.setText("Title:");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 269, -1, 23));

        servingNoLabel.setBackground(new java.awt.Color(51, 0, 153));
        servingNoLabel.setFont(new java.awt.Font("New Peninim MT", 2, 12)); // NOI18N
        servingNoLabel.setForeground(new java.awt.Color(102, 0, 102));
        servingNoLabel.setText("No. of Servings:");
        add(servingNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 303, -1, 23));

        glutenLabel.setBackground(new java.awt.Color(51, 0, 153));
        glutenLabel.setFont(new java.awt.Font("New Peninim MT", 2, 12)); // NOI18N
        glutenLabel.setForeground(new java.awt.Color(102, 0, 102));
        glutenLabel.setText("Is Gluten free ?");
        add(glutenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 335, -1, 23));

        difficultyLabel.setBackground(new java.awt.Color(51, 0, 153));
        difficultyLabel.setFont(new java.awt.Font("New Peninim MT", 2, 12)); // NOI18N
        difficultyLabel.setForeground(new java.awt.Color(102, 0, 102));
        difficultyLabel.setText("Difficulty Level:");
        add(difficultyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 365, -1, 23));

        catFoodLabel.setBackground(new java.awt.Color(51, 0, 153));
        catFoodLabel.setFont(new java.awt.Font("New Peninim MT", 2, 12)); // NOI18N
        catFoodLabel.setForeground(new java.awt.Color(102, 0, 102));
        catFoodLabel.setText("Category of Food:");
        add(catFoodLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, 23));

        imgLabel.setBackground(new java.awt.Color(51, 0, 153));
        imgLabel.setFont(new java.awt.Font("New Peninim MT", 2, 12)); // NOI18N
        imgLabel.setForeground(new java.awt.Color(102, 0, 102));
        imgLabel.setText("Recipe Picture:");
        add(imgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 341, -1, 23));

        ingredientsLabel.setBackground(new java.awt.Color(51, 0, 153));
        ingredientsLabel.setFont(new java.awt.Font("New Peninim MT", 2, 12)); // NOI18N
        ingredientsLabel.setForeground(new java.awt.Color(102, 0, 102));
        ingredientsLabel.setText("No. of Ingredients:");
        add(ingredientsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 403, -1, 23));

        descriptionLabel.setBackground(new java.awt.Color(51, 0, 153));
        descriptionLabel.setFont(new java.awt.Font("New Peninim MT", 2, 12)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(102, 0, 102));
        descriptionLabel.setText("Description:");
        add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 303, -1, 23));

        chefFirstNameField.setBackground(new java.awt.Color(204, 204, 255));
        chefFirstNameField.setFont(new java.awt.Font("Hiragino Sans GB", 0, 13)); // NOI18N
        chefFirstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chefFirstNameFieldActionPerformed(evt);
            }
        });
        add(chefFirstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 36, 272, -1));

        chefLastNameField.setBackground(new java.awt.Color(204, 204, 255));
        chefLastNameField.setFont(new java.awt.Font("Hiragino Sans GB", 0, 13)); // NOI18N
        chefLastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chefLastNameFieldActionPerformed(evt);
            }
        });
        add(chefLastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 69, 272, -1));

        chefUserNameField.setBackground(new java.awt.Color(204, 204, 255));
        chefUserNameField.setFont(new java.awt.Font("Hiragino Sans GB", 0, 13)); // NOI18N
        chefUserNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chefUserNameFieldActionPerformed(evt);
            }
        });
        add(chefUserNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 102, 272, -1));

        chefEmailField.setBackground(new java.awt.Color(204, 204, 255));
        chefEmailField.setFont(new java.awt.Font("Hiragino Sans GB", 0, 13)); // NOI18N
        chefEmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chefEmailFieldActionPerformed(evt);
            }
        });
        add(chefEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 272, -1));

        servingsField.setBackground(new java.awt.Color(204, 204, 255));
        servingsField.setFont(new java.awt.Font("Hiragino Sans GB", 0, 13)); // NOI18N
        servingsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servingsFieldActionPerformed(evt);
            }
        });
        add(servingsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 302, 154, -1));

        chefPhoneField.setBackground(new java.awt.Color(204, 204, 255));
        chefPhoneField.setFont(new java.awt.Font("Hiragino Sans GB", 0, 13)); // NOI18N
        chefPhoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chefPhoneFieldActionPerformed(evt);
            }
        });
        add(chefPhoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 272, -1));

        recipeTitleField.setBackground(new java.awt.Color(204, 204, 255));
        recipeTitleField.setFont(new java.awt.Font("Hiragino Sans GB", 0, 13)); // NOI18N
        recipeTitleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recipeTitleFieldActionPerformed(evt);
            }
        });
        add(recipeTitleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 269, 154, -1));

        ingredientsField.setBackground(new java.awt.Color(204, 204, 255));
        ingredientsField.setFont(new java.awt.Font("Hiragino Sans GB", 0, 13)); // NOI18N
        ingredientsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredientsFieldActionPerformed(evt);
            }
        });
        add(ingredientsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 399, 154, -1));

        difficultyField.setBackground(new java.awt.Color(204, 204, 255));
        difficultyField.setFont(new java.awt.Font("Hiragino Sans GB", 0, 13)); // NOI18N
        difficultyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difficultyFieldActionPerformed(evt);
            }
        });
        add(difficultyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 364, 154, -1));

        categoryFoodField.setBackground(new java.awt.Color(204, 204, 255));
        categoryFoodField.setFont(new java.awt.Font("Hiragino Sans GB", 0, 13)); // NOI18N
        categoryFoodField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryFoodFieldActionPerformed(evt);
            }
        });
        add(categoryFoodField, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 269, 154, -1));

        descriptionField.setBackground(new java.awt.Color(204, 204, 255));
        descriptionField.setFont(new java.awt.Font("Hiragino Sans GB", 0, 13)); // NOI18N
        descriptionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionFieldActionPerformed(evt);
            }
        });
        add(descriptionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 302, 154, -1));

        yesNoButtonGroup.add(yesRadioButton);
        yesRadioButton.setFont(new java.awt.Font("New Peninim MT", 2, 12)); // NOI18N
        yesRadioButton.setText("Yes");
        yesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesRadioButtonActionPerformed(evt);
            }
        });
        add(yesRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 339, -1, -1));

        yesNoButtonGroup.add(noRadioButton);
        noRadioButton.setFont(new java.awt.Font("New Peninim MT", 2, 12)); // NOI18N
        noRadioButton.setText("No");
        add(noRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 339, -1, -1));

        browseBtn.setBackground(new java.awt.Color(204, 204, 255));
        browseBtn.setText("Browse");
        browseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtnActionPerformed(evt);
            }
        });
        add(browseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 341, -1, -1));
        add(imgDisplayField, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 370, 154, 119));

        saveBtn.setBackground(new java.awt.Color(204, 204, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        addRecipeBtn.setBackground(new java.awt.Color(204, 204, 255));
        addRecipeBtn.setText("Add Recipe");
        addRecipeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRecipeBtnActionPerformed(evt);
            }
        });
        add(addRecipeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void chefFirstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chefFirstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chefFirstNameFieldActionPerformed

    private void chefLastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chefLastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chefLastNameFieldActionPerformed

    private void chefUserNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chefUserNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chefUserNameFieldActionPerformed

    private void chefEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chefEmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chefEmailFieldActionPerformed

    private void servingsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servingsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_servingsFieldActionPerformed

    private void chefPhoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chefPhoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chefPhoneFieldActionPerformed

    private void recipeTitleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recipeTitleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recipeTitleFieldActionPerformed

    private void ingredientsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredientsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingredientsFieldActionPerformed

    private void difficultyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_difficultyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_difficultyFieldActionPerformed

    private void categoryFoodFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryFoodFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryFoodFieldActionPerformed

    private void descriptionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionFieldActionPerformed

    private void yesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesRadioButtonActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:

        chefUserNameField.setEnabled(false);
        String firstName = chefFirstNameField.getText();
        String lastName = chefLastNameField.getText();
        String randomUserName = UUID.randomUUID().toString();
        chefUserNameField.setText(randomUserName);

        String email = chefEmailField.getText();
        String phone = chefPhoneField.getText();

        boolean isFirstNameValid = this.validation.checkName(firstName);
        boolean isLastNameValid = this.validation.checkName(lastName);
        boolean isEmailValid = this.validation.checkEmail(email);
        boolean isPhoneValid = this.validation.checkPhone(phone);

        if (isFirstNameValid && isLastNameValid && isEmailValid && isPhoneValid) {
            this.chefRecipeDetails.setChefFirstName(firstName);
            this.chefRecipeDetails.setChefLastName(lastName);
            this.chefRecipeDetails.setUserName(randomUserName);
            this.chefRecipeDetails.setEmail(email);
            this.chefRecipeDetails.setPhoneNo(phone);
            JOptionPane.showMessageDialog(null, "saved!");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void addRecipeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRecipeBtnActionPerformed
        // TODO add your handling code here:
        String title = recipeTitleField.getText();
        String noServings = servingsField.getText();
        String difficulty = difficultyField.getText();
        String ingredientsNo = ingredientsField.getText();
        String foodCategory = categoryFoodField.getText();
        String description = descriptionField.getText();
        if (yesRadioButton.isSelected()) {
            this.glutenFree = true;
        }
        if (noRadioButton.isSelected()) {
            this.glutenFree = false;
        }

        boolean isTitleValid = this.validation.checkNullEmpty(title);
        boolean isServingsValid = this.validation.checkNoNegativeZero(String.valueOf(noServings));
        boolean isDifficultyValid = this.validation.checkRange(String.valueOf(difficulty));
        boolean isIngredientsValid = this.validation.checkNoNegativeZero(String.valueOf(ingredientsNo));
        boolean isCategoryFieldValid = this.validation.checkNullEmpty(foodCategory);
        boolean isDescriptionValid = this.validation.checkNullEmpty(description);
        boolean isGlutenValid = this.validation.checkNullEmpty(String.valueOf(this.glutenFree));
        boolean isImgValid = this.validation.checkNullEmpty(this.selectedPath);

        if (isTitleValid && isServingsValid && isDifficultyValid && isIngredientsValid && isCategoryFieldValid && isDescriptionValid && isGlutenValid && isImgValid) {

            Recipe recipe = this.chefRecipeDetails.createRecipe(title, Integer.valueOf(noServings), this.glutenFree, Float.valueOf(difficulty), Double.valueOf(ingredientsNo), foodCategory, description, this.selectedPath);
            JOptionPane.showMessageDialog(null, "Recipe Added");
        }
    }//GEN-LAST:event_addRecipeBtnActionPerformed

    private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImageFile = new JFileChooser();
        //Filter image extensions
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);

        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
            File selectedImageFile = browseImageFile.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();
            this.selectedPath = selectedImagePath;
            ImageIcon ii = new ImageIcon(this.selectedPath);
            Image image = ii.getImage().getScaledInstance(imgDisplayField.getWidth(), imgDisplayField.getHeight(), Image.SCALE_SMOOTH);

            imgDisplayField.setIcon(new ImageIcon(image));
            JOptionPane.showMessageDialog(null, "Image Added!");
    }//GEN-LAST:event_browseBtnActionPerformed

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRecipeBtn;
    private javax.swing.JButton browseBtn;
    private javax.swing.JLabel catFoodLabel;
    private javax.swing.JTextField categoryFoodField;
    private javax.swing.JTextField chefEmailField;
    private javax.swing.JTextField chefFirstNameField;
    private javax.swing.JLabel chefFirstNameLabel;
    private javax.swing.JTextField chefLastNameField;
    private javax.swing.JLabel chefLastNameLabel;
    private javax.swing.JTextField chefPhoneField;
    private javax.swing.JTextField chefUserNameField;
    private javax.swing.JLabel chefUserNameLabel;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JTextField descriptionField;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField difficultyField;
    private javax.swing.JLabel difficultyLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel glutenLabel;
    private javax.swing.JLabel header;
    private javax.swing.JLabel imgDisplayField;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JTextField ingredientsField;
    private javax.swing.JLabel ingredientsLabel;
    private javax.swing.JRadioButton noRadioButton;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel recipeLabel;
    private javax.swing.JTextField recipeTitleField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel servingNoLabel;
    private javax.swing.JTextField servingsField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.ButtonGroup yesNoButtonGroup;
    private javax.swing.JRadioButton yesRadioButton;
    // End of variables declaration//GEN-END:variables
}
