/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Applicant;
import Model.Business;
import Model.Validation;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nishipancholi
 */
public class SearchAppJPanel extends javax.swing.JPanel {
    
    private Business business;
    DefaultTableModel nameTableModel;
    DefaultTableModel idTableModel;
    private Validation validation;

    /**
     * Creates new form SearchAppJPanel
     */
    public SearchAppJPanel() {
        initComponents();
    }

    SearchAppJPanel(Business business) {
       initComponents();
       this.business=business;
       this.nameTableModel= (DefaultTableModel) nameTable.getModel();
       this.idTableModel= (DefaultTableModel) idTable.getModel();
       this.validation= new Validation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        nameTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        idTable = new javax.swing.JTable();
        nameField = new javax.swing.JTextField();
        showNameBtn = new javax.swing.JButton();
        showIdBtn = new javax.swing.JButton();
        idField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "App Id", "App Name", "Owner First Name", "Owner Last Name", "Associated Pet"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(nameTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 650, 190));

        idTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "App Id", "App Name", "Owner First Name", "Owner Last Name", "Associated Pet"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(idTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 650, 190));
        add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 270, -1));

        showNameBtn.setText("Show By Name");
        showNameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showNameBtnActionPerformed(evt);
            }
        });
        add(showNameBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 120, -1));

        showIdBtn.setText("Show By Id");
        showIdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showIdBtnActionPerformed(evt);
            }
        });
        add(showIdBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 110, -1));
        add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 270, -1));

        jLabel1.setText("Search By Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel2.setText("Search By Id:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void showNameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showNameBtnActionPerformed
        // TODO add your handling code here:
        nameTableModel.setRowCount(0);
        String name= nameField.getText();
        ArrayList<Applicant> applications=this.business.getApplicantDirectory().findByName(name);
        if(applications.size()>0){
            for (Applicant app:applications){
                
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(app.getApplicationDate());
                Object row[]= new Object[5];
                row[0]=app;
                row[1]=date;
                row[2]=app.getOwnerFirstName();
                row[3]=app.getOwnerLastName();
                row[4]=app.getPetDetails().getPetName();
                
                nameTableModel.addRow(row);
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"No Such Insurance Application Found");
        }
        
    }//GEN-LAST:event_showNameBtnActionPerformed

    private void showIdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showIdBtnActionPerformed
        // TODO add your handling code here:
        idTableModel.setRowCount(0);
        String id= idField.getText();
        Applicant application=this.business.getApplicantDirectory().findById(Integer.valueOf(id));
        if(application!=null){
                
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(application.getApplicationDate());
                Object row[]= new Object[5];
                row[0]=application;
                row[1]=date;
                row[2]=application.getOwnerFirstName();
                row[3]=application.getOwnerLastName();
                row[4]=application.getPetDetails().getPetName();
                
                idTableModel.addRow(row);
        }
        else{
            JOptionPane.showMessageDialog(null,"No Such Insurance Application Found");
        }
        
    }//GEN-LAST:event_showIdBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idField;
    private javax.swing.JTable idTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameField;
    private javax.swing.JTable nameTable;
    private javax.swing.JButton showIdBtn;
    private javax.swing.JButton showNameBtn;
    // End of variables declaration//GEN-END:variables
}
