/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Business;
import Model.PlanDetail;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nishipancholi
 */
public class UpdateInsPlansJPanel extends javax.swing.JPanel {
    private Business business;
    DefaultTableModel planTableModel;
    private PlanDetail selectedPlan;

    /**
     * Creates new form UpdateInsPlansJPanel
     */
    public UpdateInsPlansJPanel() {
        initComponents();
    }

    UpdateInsPlansJPanel(Business business) {
        initComponents();
        this.business=business;
        this.planTableModel=(DefaultTableModel) planTable.getModel();
        displayPlans();
    }
    
    public void displayPlans(){
        ArrayList<PlanDetail> plans= this.business.getInsurancePlan().getInsurancePlanList();
        if(plans.size()>0){
            planTableModel.setRowCount(0);
            for(PlanDetail plan: plans){
                Object row[]= new Object[4];
                row[0]=plan;
                row[1]=plan.getPlanName();
                row[2]=plan.getCostPerMonth();
                row[3]=plan.getCostPerAnnum();
                
                planTableModel.addRow(row);
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Empty List");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        planTable = new javax.swing.JTable();
        idLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        monthlyCostLabel = new javax.swing.JLabel();
        annualCostLabel = new javax.swing.JLabel();
        annualCostField = new javax.swing.JTextField();
        planIdField = new javax.swing.JTextField();
        planNameField = new javax.swing.JTextField();
        monthlyCostField = new javax.swing.JTextField();
        updatePlanBtn = new javax.swing.JButton();
        displayPlanBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        planTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Monthly Cost", "Annual Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Float.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(planTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 350, 300));

        idLabel.setText("ID");
        jPanel1.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        nameLabel.setText("Name");
        jPanel1.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        monthlyCostLabel.setText("Monthly Cost");
        jPanel1.add(monthlyCostLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        annualCostLabel.setText("Annual Cost");
        jPanel1.add(annualCostLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        annualCostField.setEnabled(false);
        jPanel1.add(annualCostField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 140, 30));

        planIdField.setEnabled(false);
        jPanel1.add(planIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 140, 30));
        jPanel1.add(planNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 140, 30));

        monthlyCostField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                monthlyCostFieldFocusLost(evt);
            }
        });
        jPanel1.add(monthlyCostField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 140, 30));

        updatePlanBtn.setText("Update Plan");
        updatePlanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePlanBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updatePlanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        displayPlanBtn.setText("Display");
        displayPlanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayPlanBtnActionPerformed(evt);
            }
        });
        jPanel1.add(displayPlanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void displayPlanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayPlanBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = planTable.getSelectedRow();
        if(selectedRow >= 0){
            this.selectedPlan= (PlanDetail) planTable.getValueAt(selectedRow,0);
            planIdField.setText(String.valueOf(this.selectedPlan.getPlanId()));
            planNameField.setText(this.selectedPlan.getPlanName());
            monthlyCostField.setText(String.valueOf(this.selectedPlan.getCostPerMonth()));
            annualCostField.setText(String.valueOf(this.selectedPlan.getCostPerAnnum()));
        }
        else{
            JOptionPane.showMessageDialog(null,"Please Select Row");
        }
    }//GEN-LAST:event_displayPlanBtnActionPerformed

    private void updatePlanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePlanBtnActionPerformed
        // TODO add your handling code here:
        this.selectedPlan.setPlanName(planNameField.getText());
        this.selectedPlan.setCostPerMonth(Float.valueOf(monthlyCostField.getText()));
        this.selectedPlan.setCostPerAnnum(Float.valueOf(annualCostField.getText()));
        displayPlans();
    }//GEN-LAST:event_updatePlanBtnActionPerformed

    private void monthlyCostFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthlyCostFieldFocusLost
        // TODO add your handling code here:
        float costPerMonth=Float.valueOf(monthlyCostField.getText());
        float costPerAnnum= costPerMonth*12;
        annualCostField.setText(String.valueOf((costPerAnnum)));
    }//GEN-LAST:event_monthlyCostFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField annualCostField;
    private javax.swing.JLabel annualCostLabel;
    private javax.swing.JButton displayPlanBtn;
    private javax.swing.JLabel idLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField monthlyCostField;
    private javax.swing.JLabel monthlyCostLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField planIdField;
    private javax.swing.JTextField planNameField;
    private javax.swing.JTable planTable;
    private javax.swing.JButton updatePlanBtn;
    // End of variables declaration//GEN-END:variables
}
