/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Customer;
import Model.DeliveryPackage;
import Model.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author nishipancholi
 */
public class CreateJPanel extends javax.swing.JPanel {
    private DeliveryPackage deliveryPackage;

    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel() {
        initComponents();
    }
    
    CreateJPanel(DeliveryPackage deliveryPackage){
        initComponents();
        this.deliveryPackage= deliveryPackage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        packageIdField = new javax.swing.JTextField();
        weightField = new javax.swing.JTextField();
        productIDField = new javax.swing.JTextField();
        productNameField = new javax.swing.JTextField();
        productPriceField = new javax.swing.JTextField();
        customerNameField = new javax.swing.JTextField();
        customerIDField = new javax.swing.JTextField();
        packageIDLabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        prodIDLabel = new javax.swing.JLabel();
        prodNameLabel = new javax.swing.JLabel();
        prodPriceLabel = new javax.swing.JLabel();
        CustomerNameLabel = new javax.swing.JLabel();
        CustIDLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        AddProductButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 153));

        packageIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                packageIdFieldFocusLost(evt);
            }
        });

        weightField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                weightFieldFocusLost(evt);
            }
        });

        productIDField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                productIDFieldFocusLost(evt);
            }
        });

        productNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                productNameFieldFocusLost(evt);
            }
        });

        productPriceField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                productPriceFieldFocusLost(evt);
            }
        });

        customerNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                customerNameFieldFocusLost(evt);
            }
        });

        customerIDField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                customerIDFieldFocusLost(evt);
            }
        });

        packageIDLabel.setText("Package ID");

        weightLabel.setText("Weight");

        prodIDLabel.setText("ProdID");

        prodNameLabel.setText("ProdName");

        prodPriceLabel.setText("ProductPrice");

        CustomerNameLabel.setText("Customer Name");

        CustIDLabel.setText("Customer ID");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        AddProductButton.setText("Add Product");
        AddProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(packageIDLabel)
                            .addComponent(weightLabel)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(prodNameLabel)
                        .addComponent(prodPriceLabel)
                        .addComponent(prodIDLabel)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(weightField, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(packageIdField)
                            .addComponent(productIDField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CustomerNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CustIDLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(productPriceField)
                    .addComponent(productNameField))
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(saveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddProductButton)
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(customerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(packageIDLabel)
                        .addComponent(CustomerNameLabel))
                    .addComponent(packageIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(customerIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(weightLabel)
                        .addComponent(CustIDLabel))
                    .addComponent(weightField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prodIDLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(productIDField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prodNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(productNameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodPriceLabel))
                .addGap(7, 7, 7)
                .addComponent(AddProductButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        String id=packageIdField.getText();
        String weight=weightField.getText();
        String customerId=customerIDField.getText();
        String customerName=customerNameField.getText();
        
        
        this.deliveryPackage.setPackageId(Integer.valueOf(id));
        this.deliveryPackage.setPackageWeight(Double.valueOf(weight));
        
        
        
        Customer customer= this.deliveryPackage.getCustomer();
        customer.setCustomerId(Integer.valueOf(customerId));
        customer.setFullName(customerName);
        
        JOptionPane.showMessageDialog(null,"saved!");
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void AddProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductButtonActionPerformed
        // TODO add your handling code here:
        
        String productId= productIDField.getText();
        String productName=productNameField.getText();
        String productPrice= productPriceField.getText();
        
        Product product= this.deliveryPackage.createProduct(Integer.valueOf(productId),productName,Double.valueOf(productPrice));
        
        JOptionPane.showMessageDialog(null,"Product Added");
    }//GEN-LAST:event_AddProductButtonActionPerformed

    private void packageIdFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_packageIdFieldFocusLost
        // TODO add your handling code here:
        String packageId=packageIdField.getText();
        
        if(packageId != null && packageId.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill out the Package ID");
        }
    }//GEN-LAST:event_packageIdFieldFocusLost

    private void customerNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerNameFieldFocusLost
        // TODO add your handling code here:
        String customerName=customerNameField.getText();
        
        if(customerName != null && customerName.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill out the Customer Name");
        }
    }//GEN-LAST:event_customerNameFieldFocusLost

    private void weightFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_weightFieldFocusLost
        // TODO add your handling code here:
        String weight=weightField.getText();
        
        if(weight != null && weight.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill out the Weight");
        }
    }//GEN-LAST:event_weightFieldFocusLost

    private void customerIDFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerIDFieldFocusLost
        // TODO add your handling code here:
        String customerID=customerIDField.getText();
        
        if(customerID != null && customerID.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill out the Customer ID");
        }
    }//GEN-LAST:event_customerIDFieldFocusLost

    private void productIDFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productIDFieldFocusLost
        // TODO add your handling code here:
         String productID=productIDField.getText();
        
        if(productID != null && productID.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill out the Product ID");
        }
    }//GEN-LAST:event_productIDFieldFocusLost

    private void productNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productNameFieldFocusLost
        // TODO add your handling code here:
        String productName=productNameField.getText();
        
        if(productName != null && productName.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill out the Product Name");
        }
    }//GEN-LAST:event_productNameFieldFocusLost

    private void productPriceFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productPriceFieldFocusLost
        // TODO add your handling code here:
         String productPrice=productPriceField.getText();
        
        if(productPrice != null && productPrice.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill out the Product Price");
        }
    }//GEN-LAST:event_productPriceFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProductButton;
    private javax.swing.JLabel CustIDLabel;
    private javax.swing.JLabel CustomerNameLabel;
    private javax.swing.JTextField customerIDField;
    private javax.swing.JTextField customerNameField;
    private javax.swing.JLabel packageIDLabel;
    private javax.swing.JTextField packageIdField;
    private javax.swing.JLabel prodIDLabel;
    private javax.swing.JLabel prodNameLabel;
    private javax.swing.JLabel prodPriceLabel;
    private javax.swing.JTextField productIDField;
    private javax.swing.JTextField productNameField;
    private javax.swing.JTextField productPriceField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField weightField;
    private javax.swing.JLabel weightLabel;
    // End of variables declaration//GEN-END:variables
}
