/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Customer;
import Model.DeliveryPackage;
import Model.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author nishipancholi
 */
public class DisplayJPanel extends javax.swing.JPanel {

    private DeliveryPackage deliveryPackage;

    /**
     * Creates new form DisplayJPanel
     */
    public DisplayJPanel() {
        initComponents();
    }

    DisplayJPanel(DeliveryPackage deliveryPackage) {
        initComponents();
        this.deliveryPackage = deliveryPackage;
        viewDetails(deliveryPackage);
        viewProductList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        packageIdField = new javax.swing.JTextField();
        weightField = new javax.swing.JTextField();
        productIDField = new javax.swing.JTextField();
        productNameField = new javax.swing.JTextField();
        productPriceField = new javax.swing.JTextField();
        customerNameField = new javax.swing.JTextField();
        customerIDField = new javax.swing.JTextField();
        packageIDLabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        prodIDLabel = new javax.swing.JLabel();
        prodNameLabel = new javax.swing.JLabel();
        prodPriceLabel = new javax.swing.JLabel();
        CustomerNameLabel = new javax.swing.JLabel();
        CustIDLabel = new javax.swing.JLabel();
        showButton = new javax.swing.JButton();
        productComboBox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(102, 255, 153));

        packageIDLabel.setText("Package ID");

        weightLabel.setText("Weight");

        prodIDLabel.setText("ProdID");

        prodNameLabel.setText("ProdName");

        prodPriceLabel.setText("ProductPrice");

        CustomerNameLabel.setText("Customer Name");

        CustIDLabel.setText("Customer ID");

        showButton.setText("Show");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(packageIDLabel)
                    .addComponent(weightLabel)
                    .addComponent(prodIDLabel)
                    .addComponent(prodNameLabel)
                    .addComponent(prodPriceLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(weightField, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(packageIdField)
                            .addComponent(productIDField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CustomerNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CustIDLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerIDField))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(productPriceField)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(productNameField)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(productComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(showButton)
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(customerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(packageIDLabel)
                        .addComponent(CustomerNameLabel))
                    .addComponent(packageIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(customerIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(weightLabel)
                        .addComponent(CustIDLabel))
                    .addComponent(weightField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showButton)
                    .addComponent(productComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodIDLabel)
                    .addComponent(productIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prodNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(productNameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodPriceLabel)
                    .addComponent(productPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        // TODO add your handling code here:
        productIDField.setEnabled(false);
        productNameField.setEnabled(false);
        productPriceField.setEnabled(false);

        int pid = (int) productComboBox.getSelectedItem();
        Product prod = this.deliveryPackage.findProduct(pid);
        if (!prod.equals(null)) {
            productIDField.setText(String.valueOf(pid));
            productNameField.setText(prod.getProdName());
            productPriceField.setText(String.valueOf(prod.getProdPrice()));
        } else {
            JOptionPane.showMessageDialog(null, "No Product Found!");
        }

    }//GEN-LAST:event_showButtonActionPerformed
    public void viewDetails(DeliveryPackage deliveryPackage) {
        packageIdField.setEnabled(false);
        weightField.setEnabled(false);
        customerIDField.setEnabled(false);
        customerNameField.setEnabled(false);
        
        packageIdField.setText(String.valueOf(this.deliveryPackage.getPackageId()));
        weightField.setText(String.valueOf(this.deliveryPackage.getPackageWeight()));

        Customer customer = this.deliveryPackage.getCustomer();
        customerIDField.setText(String.valueOf(customer.getCustomerId()));
        customerNameField.setText(String.valueOf(customer.getFullName()));

    }

    public void viewProductList() {
        for (Product p : this.deliveryPackage.getProductList()) {
            productComboBox.addItem(p.getProductId());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CustIDLabel;
    private javax.swing.JLabel CustomerNameLabel;
    private javax.swing.JTextField customerIDField;
    private javax.swing.JTextField customerNameField;
    private javax.swing.JLabel packageIDLabel;
    private javax.swing.JTextField packageIdField;
    private javax.swing.JLabel prodIDLabel;
    private javax.swing.JLabel prodNameLabel;
    private javax.swing.JLabel prodPriceLabel;
    private javax.swing.JComboBox productComboBox;
    private javax.swing.JTextField productIDField;
    private javax.swing.JTextField productNameField;
    private javax.swing.JTextField productPriceField;
    private javax.swing.JButton showButton;
    private javax.swing.JTextField weightField;
    private javax.swing.JLabel weightLabel;
    // End of variables declaration//GEN-END:variables
}
