/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.LibrarianWorkArea;

import AppSystem.ApplicationSystem;
import Author.Author;
import Books.Book;
import Genres.Genre;
import LibrarianArea.Branch;
import LibrarianArea.UserAccount;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nishipancholi
 */
public class BookJPanel extends javax.swing.JPanel {
        private UserAccount useraccount;
        private ApplicationSystem system;
        DefaultTableModel tableModel;

    /**
     * Creates new form BookJPanel
     */
    public BookJPanel() {
        initComponents();
    }

    BookJPanel(ApplicationSystem system, UserAccount useraccount) {
        initComponents();
        this.system = system;
        this.useraccount = useraccount;
        this.tableModel = (DefaultTableModel) bookTable.getModel();
        populateAuthorDropdown();
        populateGenreDropdown();
        populate();
    }
    
    public void populate() {
        tableModel.setRowCount(0);
        ArrayList<Branch> branchList = this.system.getBranchList();
        for(Branch branch: branchList){
            ArrayList<Book> books=branch.getLibrary().getBookdirectory().getBooklist();
            for(Book b: books){
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(b.getRegistrationDate());
                Object[] row = new Object[9];
            
                row[0] = b.getSerialNumber();
                row[1] = b;
                row[2] = date;
                row[3] = b.getPagesNo();
                row[4] = b.getBindingType();
                row[5] = b.getLanguage();
                row[6] = b.getAuthor().getAuthorName();
                row[7] = b.getGenre().getGenreName();
                row[8] = b.isIsAvailable();
                
                tableModel.addRow(row);
            }
        }
        
    }

    public void populateAuthorDropdown(){
        
        ArrayList<Branch> branchDetail= this.system.getBranchList();
        
        for(Branch b:branchDetail){
            ArrayList<Author> authList= b.getLibrary().getAuthorDirectory().getAuthorlist();
            for(Author auth:authList){
               authorComboBox.addItem(auth); 
            }
            
        }
    }
    
    public void populateGenreDropdown(){
        
        ArrayList<Branch> branchDetail= this.system.getBranchList();
        
        for(Branch b:branchDetail){
            ArrayList<Genre> genreList= b.getLibrary().getGenreDirectory().getGenrelist();
            for(Genre gen:genreList){
               genreComboBox.addItem(gen); 
            }
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldLanguage = new javax.swing.JTextField();
        fieldBookName = new javax.swing.JTextField();
        fieldPageNumber = new javax.swing.JTextField();
        fieldBindingType = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        genreComboBox = new javax.swing.JComboBox();
        authorComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addBookBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Add Book");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        fieldLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLanguageActionPerformed(evt);
            }
        });
        add(fieldLanguage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 180, -1));

        fieldBookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBookNameActionPerformed(evt);
            }
        });
        add(fieldBookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 180, -1));

        fieldPageNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPageNumberActionPerformed(evt);
            }
        });
        add(fieldPageNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 180, -1));

        fieldBindingType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBindingTypeActionPerformed(evt);
            }
        });
        add(fieldBindingType, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 180, -1));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 180, -1));

        add(genreComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 190, -1));

        add(authorComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 190, -1));

        jLabel2.setText("Choose Genre");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        jLabel3.setText("Choose Author");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        jLabel4.setText("Language:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 20));

        jLabel5.setText("Book Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 20));

        jLabel6.setText("Registration Date:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jLabel7.setText("Page Number:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 20));

        jLabel8.setText("Binding Type:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 20));

        addBookBtn.setText("ADD BOOK");
        addBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookBtnActionPerformed(evt);
            }
        });
        add(addBookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Book Name", "Registraion Date", "Page No", "Binding Type", "Language", "Author", "Genre", "isAvailable"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bookTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 620, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLanguageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLanguageActionPerformed

    private void fieldBookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBookNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBookNameActionPerformed

    private void fieldPageNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPageNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPageNumberActionPerformed

    private void fieldBindingTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBindingTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBindingTypeActionPerformed

    private void addBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookBtnActionPerformed
        // TODO add your handling code here:
        String bookName= fieldBookName.getText();
        String pageNo= fieldPageNumber.getText();
        String bindingType= fieldBindingType.getText();
        String language= fieldLanguage.getText();
        Date registrationDate= jDateChooser1.getDate();
        Author authorDetails =(Author) authorComboBox.getSelectedItem();
        Genre genreDetails =(Genre) genreComboBox.getSelectedItem();
        
        ArrayList<Branch> branchList = this.system.getBranchList();
        for(Branch branch: branchList){
            branch.getLibrary().getBookdirectory().createBook(bookName, registrationDate, true, Integer.valueOf(pageNo), bindingType,language, authorDetails, genreDetails);
            JOptionPane.showMessageDialog(null, "Book Created.");
            populate();    
        }
    }//GEN-LAST:event_addBookBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookBtn;
    private javax.swing.JComboBox authorComboBox;
    private javax.swing.JTable bookTable;
    private javax.swing.JTextField fieldBindingType;
    private javax.swing.JTextField fieldBookName;
    private javax.swing.JTextField fieldLanguage;
    private javax.swing.JTextField fieldPageNumber;
    private javax.swing.JComboBox genreComboBox;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
