/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.LibrarianWorkArea;

import AppSystem.ApplicationSystem;
import LibrarianArea.UserAccount;

/**
 *
 * @author nishipancholi
 */
public class RequestsJPanel extends javax.swing.JPanel {
        private UserAccount useraccount;
        private ApplicationSystem system;
//       DefaultTableModel tableModel;

    /**
     * Creates new form GenreJPanel
     */
    public RequestsJPanel() {
        initComponents();
    }

    RequestsJPanel(ApplicationSystem system, UserAccount useraccount) {
        initComponents();
        this.system = system;
        this.useraccount = useraccount;
//        this.tableModel = (DefaultTableModel) userTable.getModel();
//        
//        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
